# Generated by Django 5.2.8 on 2025-11-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='show_hours',
            field=models.BooleanField(default=True, help_text='آیا ساعات کاری در منو نمایش داده شود؟', verbose_name='نمایش ساعات کاری'),
        ),
        migrations.AddField(
            model_name='businesshour',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='آیا این ساعت کاری در منو نمایش داده شود؟', verbose_name='نمایش در منو'),
        ),
    ]
